### ISSUE TITLE
Como sigues el tutorial desde ubuntu

### ISSUE THREAD

**Issue by irvinmarceloc** [DavidReveloLuna/Semantic-Segmentation-Basic-U-Net#1]
Estoy empezando en esto y la verdad no entiendo bien para que sirve conda, al principio lo estuve reemplazando con un entorno virtual en python, pero luego quedo confundido. 
¿Es lo mismo?

**Comment by DavidReveloLuna** [comment]
Hola

Efectivamente es lo mismo, la idea es generar entornos independientes donde
puedas instalar las librerías y dependencias de tu proyecto.
